const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const path=require('path');const root=path.resolve(__dirname,'..');
const app=fs.readFileSync(path.join(root,'app.js'),'utf8'),cloud=fs.readFileSync(path.join(root,'cloud.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,'HTML IDs are unique');
for(const m of (app+cloud).matchAll(/(?:on|\$)\(['"]#([\w-]+)['"]/g))assert(ids.includes(m[1]),'Missing control '+m[1]);
const stores=['visits','photos','meta','projects'];const elements=new Map();
function el(){return {children:[],append(...c){this.children.push(...c)},replaceChildren(){this.children=[]},classList:{add(){},remove(){}},textContent:'',disabled:false};}
let dbdata;let userConfirm=true;let handed=0,downloaded=0;
const context={console,Blob,File,Date,Map,Set,Uint8Array,atob,structuredClone,STORES:stores,NOTE_KEYS:['note','tag','area','sheet','owner','due','itemId'],FileReader:class{},document:{createElement:el},navigator:{},download:()=>downloaded++,confirm:()=>userConfirm,alert(){},dataEpoch:0,selectedProject:null,loadState:async()=>{},measure:async()=>({w:1,h:1}),$:id=>{if(!elements.has(id))elements.set(id,el());return elements.get(id)},dateInput:ts=>new Date(ts).toISOString().slice(0,10),blobData:async b=>'data:'+b.type+';base64,'+Buffer.from(await b.arrayBuffer()).toString('base64'),read:async n=>structuredClone(dbdata[n]),allV:async()=>structuredClone(dbdata.visits)};
context.transaction=async(names,mode,work)=>{
 const copy=structuredClone(dbdata);let error;const tx={abort(){error=new Error('aborted')},objectStore:n=>({getAll(){const q={result:structuredClone(copy[n])};queueMicrotask(()=>q.onsuccess?.());return q},put(r){const i=copy[n].findIndex(x=>x.id===r.id);if(i<0)copy[n].push(r);else copy[n][i]=r;},delete(id){copy[n]=copy[n].filter(r=>r.id!==id);}})};
 const result=work(tx);await new Promise(setImmediate);if(error)throw error;if(mode==='readwrite')dbdata=copy;return typeof result==='function'?result():result;
};
vm.createContext(context);vm.runInContext(cloud,context);vm.runInContext(app.slice(app.indexOf('function validateBackup('),app.indexOf('let dataEpoch=')),context);
const now=Date.now(),day=86400000;
const project={id:1,name:'Test Project',number:'T01',key:'number:t01'};
const item={id:'item:1:1',ref:'001.01',originVisitId:1,firstVisitNum:1,firstNoted:now-40*day,note:'Open flashing',owner:'',due:'',area:'Roof',status:'Still open',update:'',photoId:1,followupPhotoIds:[]};
const v=(id,num,closed,age,items=[])=>({id,num,projectId:1,schema:9,date:now-age*day,completedAt:closed?now-age*day:undefined,project:'Test Project',projNum:'T01',attendees:'',preparedBy:'',weather:'',temp:'',closed,itemSeq:1,items});
const blob=new Blob(['original-jpeg-bytes'],{type:'image/jpeg'});
const data={projects:[project],visits:[v(1,1,true,40,[item]),v(2,2,false,1,[{...item,status:'Not reviewed'}])],photos:[{id:1,visitId:1,ts:now-40*day,blob},{id:2,visitId:1,ts:now-40*day+1,blob}],meta:[{id:1,itemId:item.id,note:'Open flashing'},{id:2,note:'General'}]};
(async()=>{
 let plan=context.cleanupPlan(data.visits,data.photos,now);assert.equal(plan.length,1);assert.equal(plan[0].removable[0].id,2);assert.equal(plan[0].retained[0].id,1);
 assert.equal(context.cleanupPlan([v(1,1,true,29)],data.photos,now).length,0);
 assert.equal(context.cleanupPlan([v(1,1,false,40)],data.photos,now).length,0);
 assert.equal(context.cleanupPlan([v(1,1,true,30)],data.photos,now).length,1);
 dbdata=structuredClone(data);await context.removeLocalPhotos(1);assert(dbdata.photos[0].blob);assert(!dbdata.photos[1].blob);assert.equal(dbdata.photos[1].archived,true);assert.equal(dbdata.visits.length,2);assert.equal(dbdata.meta.length,2);
 dbdata.visits[1].items[0].status='Closed';await context.removeLocalPhotos(1);assert(!dbdata.photos[0].blob,'previously protected image removable after resolution');
 const original=structuredClone(data);const recovery=await context.projectRecoveryFile(original,'test');const raw=JSON.parse(await recovery.text());assert.equal(raw.data.projects.length,1);
 const validated=context.validateBackup({...structuredClone(raw),format:'rdg-sitevisit-backup'});assert.equal(await validated.photos[0].blob.text(),await blob.text());
 const other={projects:[{id:1,key:'other',name:'Other',number:'O'}],visits:[{id:50,projectId:1}],photos:[{id:80,visitId:50}],meta:[]};
 const mapped=context.remapProjectCopy(validated,other);assert.equal(mapped.projects[0].id,2);assert.equal(mapped.visits[0].id,51);assert.equal(mapped.photos[0].id,81);assert.equal(mapped.visits[1].items[0].photoId,81);assert.equal(mapped.meta[0].itemId,mapped.visits[0].items[0].id);
 assert.equal(mapped.visits[0].items[0].id,mapped.visits[1].items[0].id);assert.equal(mapped.visits[0].items[0].originVisitId,51);
 dbdata=structuredClone(other);await context.restoreProjectFile(recovery);assert(dbdata.visits.some(v=>v.id===50));assert.equal(dbdata.projects.length,2);assert.equal(dbdata.visits.length,3);
 const again=structuredClone(dbdata);userConfirm=false;await context.restoreProjectFile(recovery);assert.equal(JSON.stringify(dbdata),JSON.stringify(again));userConfirm=true;
 await context.restoreProjectFile(recovery);assert.equal(dbdata.projects.length,2);assert.equal(dbdata.visits.length,3,'replacing project does not duplicate visits');assert(dbdata.photos.some(p=>p.id===80));
 const archived=structuredClone(data);delete archived.photos[1].blob;archived.photos[1].archived=true;
 const archivedFile=await context.projectRecoveryFile(archived,'archived');const archivedRaw=JSON.parse(await archivedFile.text());context.validateBackup({...archivedRaw,format:'rdg-sitevisit-backup'});
 const corrupt=structuredClone(raw);corrupt.data.photos[0].data='bad';assert.throws(()=>context.validateBackup({...corrupt,format:'rdg-sitevisit-backup'}));
 const legacy=structuredClone(raw);legacy.version=1;context.validateBackup({...legacy,format:'rdg-sitevisit-backup'});
 const legacyBad=structuredClone(raw);legacyBad.data.visits[0].legacyReportItems='oops';assert.throws(()=>context.validateBackup({...legacyBad,format:'rdg-sitevisit-backup'}));
 const status={textContent:''};context.navigator={canShare:()=>true,share:()=>{handed++;return Promise.reject({name:'AbortError'})}};
 const button=context.saveFileButton([recovery],'Save',status);button.onclick();assert.equal(handed,1,'share invoked synchronously');await new Promise(setImmediate);assert.equal(button.disabled,false);assert.equal(status.textContent,'');
 context.navigator={canShare:()=>false};context.saveFileButton([recovery],'Save',status).onclick();assert.equal(downloaded,1);assert(status.textContent.includes('Download requested'));
 context.saveFileButton([recovery,recovery],'Save',status).onclick();assert.equal(downloaded,1,'no silent multi-download');assert(status.textContent.includes('individually'));
 const badExport=structuredClone(data);delete badExport.photos[0].blob;await assert.rejects(context.projectRecoveryFile(badExport,'bad'));
 assert(context.csvCell('=SUM(A1)').includes("'="));assert(!context.fileStem('bad/path:name').includes('/'));
 console.log('PASS: controls, 30-day boundary, no active-visit cleanup, protected evidence, confirmed removal, archived metadata, photo-byte recovery, isolated project restoration, ID remapping, cancel handling, v1 backups, corrupt recovery rejection, synchronous sharing, and download fallback.');
})().catch(e=>{console.error(e);process.exitCode=1});
